### ISSUE TITLE
Can I test SkyX V2?

### ISSUE THREAD

**Issue by CarLover014** [geofs-plugins/plugin-manager-V2#11]
Is there a way that i can run this on GeoFS now? If so, how do I do it?

**Comment by ron-popov** [comment]
The source code is open source and you can do what you want with it.  
__BUT__ we are not ready for testing yet, due to that i will post a short guide on how to install it but keep in mind that it is not finished yet and in very early alpha.  
Currently the only thing that SkyX 2 has is an additional tab in the settings menu so don't get too hyped yet.

Installation instruction :
* Download tampermonkey to your browser.
* Click on the tampermonkey icon and add a new script.
* Paste the content of ```src/base.user.js```.
* Run Geo-FS and it should work.
* Follow the in-game instructions.  

To test if it works click on the settings button and there should be a tab titled SkyX.
